version: '3.8'
services:
  despegar-db:
    image: postgres:latest
    container_name: "despegar-db"
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=despegar-db
      - DB_NAME=despegar-db
    volumes:
      - despegar-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    image: despegar/api
    container_name: "despegar-api"
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
volumes:
  despegar-db:
