version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: "despegar-db"
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

 # api:
 #   image: despegar/api
 #   container_name: "despegar-api"
 #   depends_on:
 #     - postgres
 #   env_file:
 #     - ./.env
 #   build:
 #     context: ./
 #     dockerfile: Dockerfile
 #   ports:
 #     - '3000:3000'
volumes:
  postgres:
